### ISSUE TITLE
KSP 1.11.x is borking the recovering of costs from scaled parts.

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/KSP-Recall#12]
Fellow Kerbonaut [firethorn6](https://forum.kerbalspaceprogram.com/index.php?/profile/210389-firethorn6/) have a [misbehaviour](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-ksp-144-tweakscale-under-lisias-management-2445-2021-0120/&do=findComment&comment=3933725) on his rig - as from KSP 1.11.x, the refunding at vessels recover is borked!

Evidencest:
![screenshot7](https://user-images.githubusercontent.com/64334/109468175-0336f000-7a4b-11eb-84f7-adfd9e4694a7.png)

A MK1 Pod and a Flea scaled to 2.8M (as anything bigger would  not be allowed to launch on a early career). 2848 Funds.

I launched and immediately recovered it, to get the full refund:

* 588
* 1304
* 12
* 944

And this totalled 2848 Funds. So it's working, at least on KSP 1.4.5.

So I redid the test on 1.7.3:
![screenshot11](https://user-images.githubusercontent.com/64334/109468637-a556d800-7a4b-11eb-861f-5a4c8e6e5b54.png)
![screenshot12](https://user-images.githubusercontent.com/64334/109468703-bdc6f280-7a4b-11eb-8e02-ab0c58354846.png)

And it works too. Right now I cleared something wrong on TweakScale, now I need to check if something changed on KSP itself, perhaps on 1.8.1?
![screenshot61](https://user-images.githubusercontent.com/64334/109469917-7477a280-7a4d-11eb-972f-215b1850c436.png)

Nops. Worked fine. Just for the sake of completude, I did the test on KSP 1.10.1:
![screenshot63](https://user-images.githubusercontent.com/64334/109474079-e0a8d500-7a52-11eb-8a75-e228a64b7710.png)

And again fine.

Well, gone to KSP 1.11.1 (lots of thing changed on this one, perhaps?)
![screenshot55](https://user-images.githubusercontent.com/64334/109470945-d4227d80-7a4e-11eb-8b40-955048f6698b.png)

Bingo. It's something on KSP 1.11.1. :( Interesting enough, the cost of the vessel is now 2883 (probably due the new Inventory system)

**Comment by Lisias** [comment]
Slightly better.

![screenshot67](https://user-images.githubusercontent.com/64334/109741166-49a36080-7bab-11eb-8b15-1fe0741f53d4.png)

The end result is still the same, but I further abused my way on it in order to prevent changing two fields on the Summary. Now the (improper) values are kept, making easier to track what I really did.

**Comment by Lisias** [comment]
How to check if the KSP Recall stunt is installed on your 1.11.x rig:

1) Look for this Log Entry on the KSP.log:
```
[LOG 04:11:02.071] [KSP_Recall] Version 0.0.7.0 /L *BETA* DEBUG running on KSP 1.11.1
```

2) Observe the Resouces Widget on flight, look for the `Refunding` one:
![screenshot71](https://user-images.githubusercontent.com/64334/109769050-728e1a80-7bd8-11eb-9304-c17421da71cf.png)

3) Look for the `Refunding` Resource when recovering the craft:
![screenshot72](https://user-images.githubusercontent.com/64334/109769155-96516080-7bd8-11eb-94b2-6c59a0de24d8.png)

**Comment by Lisias** [comment]
Some add'ons as PayToPlay are being ignored by `Refunding`. The reason is that `Refunding`, on its first prototype, updates itself on Launch and from there, it needs someone to "tell him" to update itself.

The solution worked fine with TweakScale (surprised? :P ) but it's cumbersome for add'ons that constantly update the part's cost, exactly the case for PayToPlay.

A better solution is to monitor when the craft is being recovered and update itself on that time, what guarantee the most updated data to be "refunded".

This is a testrun for PayToPlay, where depreciation is being applied to the Flea engine for being used:
![screenshot73](https://user-images.githubusercontent.com/64334/109873668-d5b99480-7c4c-11eb-9454-5a478411e80e.png)

The U.I. will be still "weird", with the `+-` on front of the `Refunding` "resource", but it will do as is. This is (hopefully) a temporary hack, after all.

Fix implemented on commit https://github.com/net-lisias-ksp/KSP-Recall/commit/06255bbb98e4770ad462ba2f7f6c7791c9b4dad8

**Comment by Lisias** [comment]
A new release is on the wild.

https://github.com/net-lisias-ksp/KSP-Recall/releases/tag/PRE-RELEASE%2F0.0.7.1

I will keep this Issue opened while this stunt is on tests.

**Comment by DarthPointer** [comment]
It is time I tell you I have lied. P2P does not update cost constantly, it actually changes cost max once during flight (to nullify cost). However there is no way to detect it outside P2P. And I guess at this point the fix covers most the cases if not all.

**Comment by Lisias** [comment]
Fellow Kerbonaut [firethorn6](https://forum.kerbalspaceprogram.com/index.php?/profile/210389-firethorn6/) reported a new misbehaviour, at this moment not known to be related to `Refunding` or not:

By bulding a craft using a stayputnik and a thoroughbred scaled to 10 meters, we are being charged **above** the craft cost on launching!

The stunt costs 576.300F, and on the screenshot below I have 600kF on my wallet:
![screenshot73](https://user-images.githubusercontent.com/64334/109894512-62c01600-7c6c-11eb-8bcd-7a209256aa7b.png)

The refunding stunt itself is working fine, the full costs of the vessel is being recovered:
![screenshot74](https://user-images.githubusercontent.com/64334/109894653-a286fd80-7c6c-11eb-96e6-baa004713701.png)

But note on the screenshot above that my wallet is now 576.300F, the price of the craft - what means I had no money left!!!

The price being charged on launch is bigger than the craft's price - on this case, I paid 23700F more for it.

So I redid the test, but with way more money than needed, so see exactly how much I'm being charged for this:

![screenshot76](https://user-images.githubusercontent.com/64334/109894936-1cb78200-7c6d-11eb-9393-ee124df3d0d7.png)

And my wallet, after launch, came to... **WHAT A HELL???** Zero Funds again?

![screenshot77](https://user-images.githubusercontent.com/64334/109895090-6607d180-7c6d-11eb-9799-a18b09c4d1f3.png)

Oukey, I need to reassess this situation...

**Comment by Lisias** [comment]
New test. A way cheaper craft, 5M thoroughbred costing to launch 72.300F, and with 1M on the wallet.

![screenshot78](https://user-images.githubusercontent.com/64334/109895859-bd5a7180-7c6e-11eb-9aff-9d5e36a88bd4.png)

After launch, my wallet gone down to 864.699F:
![screenshot79](https://user-images.githubusercontent.com/64334/109896027-fd215900-7c6e-11eb-8e59-29be1c4604e1.png)

So the launch cost me 1.000.000 - 864.699 = 135.301F !!!!

Hummm....  I had an idea...

**Comment by Lisias** [comment]
Found the reason.

```
[LOG 22:50:43.334] [KSP-Recall-Refunding] TRACE: Recalculate Results originalCost: 13800.0; resourceCosts:38400.0; wrongCost:-24600.0; rightCost:38400.0; fix:63000.0 ;
```

The `costfix` for this craft is 63.000F, what added to the nominal 23.700F gives the 135.301F charged on launch.

What's happening is that the charge happens on the Flight Scene, and by that point I already had initialised the `Funding` internal data.

So the solution is to do not initialise `Refunding` until the last moment it's needed...

**Comment by Lisias** [comment]
Fixed!

![screenshot80](https://user-images.githubusercontent.com/64334/109903571-b46f9d00-7c7a-11eb-8328-80ad7759722a.png)
![screenshot81](https://user-images.githubusercontent.com/64334/109903580-b76a8d80-7c7a-11eb-8c27-a3631234f309.png)
![screenshot82](https://user-images.githubusercontent.com/64334/109903598-bafe1480-7c7a-11eb-81c0-cfc870b9a330.png)

Commit https://github.com/net-lisias-ksp/KSP-Recall/commit/6a0f157d65d91acfe1bc8692252743ec0eb01f36

**Comment by Lisias** [comment]
With the [0.0.7.3](https://github.com/net-lisias-ksp/KSP-Recall/releases/tag/RELEASE%2F0.0.7.3) release publsihed, I consider this issue closed/fixed

**Comment by gotmachine** [comment]
This is a terrible, hacky and ugly solution for a very easy to solve problem.

The mistake in KSP 1.11 happens in the stock `Funding.onVesselRecoveryProcessing()` callback.
When implementing recovery of cargo parts, they somehow missed to call the original refund method with the `includeModuleCosts` arg set to true.

When `includeModuleCosts` is true, `ShipConstruction.GetPartCosts()` grab the `ProtoPartSnapshot.moduleCosts` value, itself set through the `Part.GetModuleCosts()` method that was called when the vessel was last unloaded, when the ProtoPartSnapshot was created.

They are now calling only : 
```
ShipConstruction.GetPartCosts(protoPartSnapshot, includeModuleCosts: false, availablePart, out var dryCost, out var fuelCost);
```
which causes the `ProtoPartSnapshot.moduleCosts` variable to be ignored when calculating refunding.

The solution is to create a `KSPAddon` that subscribe to the `GameEvents.onVesselRecoveryProcessing` event, adding a callback that look something like that :
```cs
private void onVesselRecoveryProcessing(ProtoVessel pv, KSP.UI.Screens.MissionRecoveryDialog mrDialog, float recoveryScore)
{
	if (pv == null)
	{
		return;
	}

	float modulesRecoveredFunds = 0f;

	foreach (ProtoPartSnapshot protoPartSnapshot in pv.GetAllProtoPartsIncludingCargo())
	{
		modulesRecoveredFunds += protoPartSnapshot.moduleCosts;
	}

	modulesRecoveredFunds *= recoveryScore;

	if (mrDialog != null && mrDialog.fundsEarned > 0f)
	{
		mrDialog.fundsEarned += modulesRecoveredFunds; // might not work if this is called before the stock callback, but this is UI only anyway.
	}

	Funding.Instance.AddFunds(modulesRecoveredFunds, TransactionReasons.VesselRecovery);
}
```
You can eventually get fancy and create a dummy `PartWidget` widget to the `MissionRecoveryDialog` to give an additional UI feedback.

Also, you should probably check the KSP version since this only apply to KSP 1.11, you can do something like that : 
```cs
Version KSPVersion = new Version(Versioning.version_major, Versioning.version_minor, Versioning.Revision);

Version MinVersion = new Version(1, 11, 0);
Version MaxVersion = new Version(1, 11, 9);

if (KSPVersion >= MinVersion && KSPVersion <= MaxVersion)
{
	// Suscribe to GameEvents.onVesselRecoveryProcessing
}
```

**Comment by Lisias** [comment]
> This is a terrible, hacky and ugly solution for a very easy to solve problem.
> 
> The mistake in KSP 1.11 happens in the stock `Funding.onVesselRecoveryProcessing()` callback.
> When implementing recovery of cargo parts, they somehow missed to call the original refund method with the `includeModuleCosts` arg set to true.
> 
> When `includeModuleCosts` is true, `ShipConstruction.GetPartCosts()` grab the `ProtoPartSnapshot.moduleCosts` value, itself set through the `Part.GetModuleCosts()` method (itself iterating on all `IPartCostModifier` modules to compute the result) that was called when the vessel was last unloaded, when the ProtoPartSnapshot was created
> 
> They are now calling only :
> 
> ```
> ShipConstruction.GetPartCosts(protoPartSnapshot, includeModuleCosts: false, availablePart, out var dryCost, out var fuelCost);
> ```
> 
> which causes the `ProtoPartSnapshot.moduleCosts` variable to be ignored when calculating refunding.
> 
> The solution is to create a `KSPAddon` that subscribe to the `GameEvents.onVesselRecoveryProcessing` event, adding a callback that look something like that (totally untested) :
> 
> ```cs
> private void onVesselRecoveryProcessing(ProtoVessel pv, KSP.UI.Screens.MissionRecoveryDialog mrDialog, float recoveryScore)
> {
> 	if (pv == null)
> 	{
> 		return;
> 	}
> 
> 	float modulesRecoveredFunds = 0f;
> 
> 	foreach (ProtoPartSnapshot protoPartSnapshot in pv.GetAllProtoPartsIncludingCargo())
> 	{
> 		modulesRecoveredFunds += protoPartSnapshot.moduleCosts;
> 	}
> 
> 	modulesRecoveredFunds *= recoveryScore;
> 
> 	if (mrDialog != null && mrDialog.fundsEarned > 0f)
> 	{
> 		mrDialog.fundsEarned += modulesRecoveredFunds; // might not work if this is called before the stock callback, but this is UI only anyway.
> 	}
> 
> 	Funding.Instance.AddFunds(modulesRecoveredFunds, TransactionReasons.VesselRecovery);
> }
> ```
> 
> You can eventually get fancy and create a dummy `PartWidget` widget to the `MissionRecoveryDialog` to give an additional UI feedback.
> 
> Also, you should probably check the KSP version since this only apply to KSP 1.11, you can do something like that :
> 
> ```cs
> Version KSPVersion = new Version(Versioning.version_major, Versioning.version_minor, Versioning.Revision);
> 
> Version MinVersion = new Version(1, 11, 0);
> Version MaxVersion = new Version(1, 11, 9);
> 
> if (KSPVersion >= MinVersion && KSPVersion <= MaxVersion)
> {
> 	// Suscribe to GameEvents.onVesselRecoveryProcessing
> }
> ```

There's no need to check for the KSP version on the Module, as they are injected selectively by the patch.

See the files:
https://github.com/net-lisias-ksp/KSP-Recall/blob/master/GameData/999_KSP-Recall/patches/refunding.cfg

'KSPRECALL-REFUNDING' is registered on ModuleManager only when the patch is needed - the decision of being applied doesn't belongs to the Module, but to some other code where better strategic decisions can be made.
