### ISSUE TITLE
Freeze on loading

### ISSUE THREAD

**Issue by Timmydiah-kerbal** [net-lisias-ksp/KSP-Recall#4]
after installing this mod, the start up loading freezes. i removed it and things work again.
tried twice.

**Comment by Lisias** [comment]
Yeah, I confirmed it.

When I internalised the KSPe dependency (using KSPe.Light.Recall), I forgot to do it on Resourceful, only the main-dll was fixed. And then I tested the thing on a dirty test bed (that had KSPe installed), and so everything worked fine for me and I didn't noticed the bork.

It's fixed for KSP Recall 0.0.2.2 - sorry for the mess.
