### ISSUE TITLE
Find a way to survive KSPCF's ~~Stupidity~~ *Less Than Smartness*.

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/KSP-Recall#62]
So, KSPCF decided to **blindly** disable KSP-Recall, whatever their fixes are active or not.

https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/124

https://github.com/KSPModdingLibs/KSPCommunityFixes/blob/1.24.6/GameData/KSPCommunityFixes/MMPatches/ModSupport/KSPRecall.cfg (currently the latest)

```
@PART[*]:HAS[@MODULE[Refunding]]:NEEDS[KSPRECALL-REFUNDING]:FINAL
{
	!MODULE[Refunding]{}
}

@KSP-Recall:AFTER[999_KSP-Recall]
{
  @INSTALLED
  {
    @Refunding = false
  }
}
```

And there's no way I can civilly overcome this crap, I will need to brute force my way on the problem.

## OBJECTIVE
Find the less brute and intrusive way to allow users to activate the updated `Refunding` if this is what they want.

Some people is going to yell on me for sure - as it would be any difference by now. :/

**Comment by gotmachine** [comment]
I really enjoy your pleasing passive-aggressive tone :)

**Comment by Lisias** [comment]
Hope to had made someone more happy today. :D

**Comment by Lisias** [comment]
Well, this is what I had done:

1. Split the current Refunding Stunt in two `PartModules`
    * One will deal exclusively to the original problem
    * The other will try to handle the `float` precision problem
2. And, yeah, a new MetaResource will be added.
    * (sigh)
3. Both `PartModules` can be individually activated or deactivated.

**Comment by Lisias** [comment]
Implemented on commit https://github.com/net-lisias-ksp/KSP-Recall/commit/6f7aa4c09ef8e543445422b493716ce70d806561

Additionally, the Meta Resources are not created anymore when they are not needed. This will shrink a bit the surface of the exposition of the ~~solution~~*hack*.

**Comment by Lisias** [comment]
Now I need to retest the following Issues:

[ ] https://github.com/net-lisias-ksp/KSP-Recall/issues/12 (KSP 1.11.x is borking the recovering of costs from scaled parts.)
[ ] https://github.com/net-lisias-ksp/KSP-Recall/issues/60 (Weird Misbehaviour on Interstellar Technologies.)

**Comment by Lisias** [comment]
Oukey. All tests are good. Closing this.
