### ISSUE TITLE
Yet a new batch of displacement problems on KSP….

### ISSUE THREAD

**Issue by Lisias** [net-lisias-ksp/KSP-Recall#65]
### Discussed in https://github.com/net-lisias-ksp/KSP-Recall/discussions/64

<div type='discussions-op-text'>

<sup>Originally posted by **Lisias** April  6, 2023</sup>
Fellow Kerbonaut [Krazy1](https://forum.kerbalspaceprogram.com/index.php?/profile/203523-krazy1/) is being bitten by some problems related to part displacements after being scaled.

[Album depicting the problem](https://imgur.com/a/th87Xfe).

Let's see what I get trying these testes on my ACP rig.

"Screenshot" of the GameData. All Add'Ons are updated to the latest:

```
total 5976
-rw-r--r--  1 lisias staff   18944 Mar 13 12:45 666_ModuleManagerWatchDog.dll
drwxr-xr-x 12 lisias staff     384 Mar 25 23:23 999_KSP-Recall
-rw-r--r--  1 lisias staff    5632 Mar 24 02:10 999_Scale_Redist.dll
drwxr-xr-x 12 lisias staff     384 Jan 30 01:37 AviationLights
drwxr-xr-x 13 lisias staff     416 Sep  8  2022 DistantObject
drwxr-xr-x 11 lisias staff     352 Jan 29 11:08 GPOSpeedPump
drwxr-xr-x 14 lisias staff     448 Aug 12  2022 HLAirshipsCore
drwxr-xr-x 15 lisias staff     480 Jul 25  2020 ImpossibleInnovations
drwxr-xr-x 11 lisias staff     352 Nov 27 23:15 KourageousTourists
-rw-r--r--  1 lisias staff  141824 Jan 14 20:34 ModuleManager.4.2.2.dll
-rw-r--r--  1 lisias staff 5513188 Apr  2 14:14 ModuleManager.ConfigCache
-rw-r--r--  1 lisias staff  260473 Apr  2 14:13 ModuleManager.ConfigSHA
-rw-r--r--  1 lisias staff    8779 Apr  2 14:14 ModuleManager.Physics
-rw-r--r--  1 lisias staff   31997 Apr  2 14:14 ModuleManager.TechTree
drwxr-xr-x  9 lisias staff     288 Nov 12 08:14 ModuleManagerWatchDog
drwxr-xr-x 28 lisias staff     896 Jan 14 20:41 Squad
drwxr-xr-x  4 lisias staff     128 Aug  4  2021 SquadExpansion
drwxr-xr-x 23 lisias staff     736 Mar 24 01:59 TweakScale
drwxr-xr-x 18 lisias staff     576 Oct 10  2021 TweakScaleCompanion
drwxr-xr-x 14 lisias staff     448 Aug  3  2022 Waterfall
drwxr-xr-x  3 lisias staff      96 Mar 24 01:59 __LOCAL
```</div>

**Comment by Lisias** [comment]
See #64 for logs, crafts and more information about the problem

**Comment by Lisias** [comment]
Well, I found the reason because the thing is screwing up the user.

What I don't understand is **why in fscking hell** this piece of krap is working fine on my rig.

**Comment by Lisias** [comment]
Commit https://github.com/net-lisias-ksp/KSP-Recall/commit/c198a1389d8db409c96061c23250c24bfbdecff3 restores the feature.

Commit https://github.com/net-lisias-ksp/KSP-Recall/commit/a08690d0f0ed21543b60528d8012db2e5d1b96e5 does a salvage on current SFS and CRAFT files affected by this huge bork of mine.

**Comment by Lisias** [comment]
Now I need to understand why in hell I didn't detected this on my Acceptance tests.

**Comment by Lisias** [comment]
**JESUS FSCKING CHRIST**. Found it.

**IT'S MODULE MANAGER**. This piece of crap fails now and then from detecting changes on the GameData, and fails to update the Config Cache.

So I had tested a bad code using an old Config Cache, because the fscking Module Manager didn't detected a change on the DLLs!!! 

I was a sinner, but I had seen the Light and now I'm a believer - because only God himself would be able to keep this Community afloat for so many years with this piece of crap being used as the most important component of the modding scene!!!

**Comment by Lisias** [comment]
The solution? Easy. I'm ditching Module Manager for good now, even on the Acceptance tests.

From now on, I will only use my own fork, and anyone asking for support will be advised to consider switching to it. My fork have this problem tackled down.

**Comment by Lisias** [comment]
There's something additional happening - I eye balled the MM (Forum) source code, and didn't found any new weakness that I had not detected before.

DIGESTs **are not** IDENTITIES, and MM (Forum) fails bitterly on recognising this fact, so evidences still pinpoint it as the source of the problem - but I will need some more digging until I'll able to pinpoint the exact piece of code that it's failing.

**Comment by Lisias** [comment]
An issue on MM/L was created, related to this happening.

https://github.com/net-lisias-ksp/ModuleManager/issues/20

**Comment by Lisias** [comment]
POST MORTEM:

About my comment on : https://github.com/net-lisias-ksp/KSP-Recall/issues/65#issuecomment-1500777219

Well… **This time** MM wasn't the responsible for the problem, it was only involved.

I created a bug on KSP-Recall where the affected `PartModule` was not being automatically activated on creation. I didn't detected the problem because I was reusing Crafts and Savegames already existents, where the `PartModule`s were already activated, and so nothing wrong happens.

But on new crafts and savegames, the affected `PartModule` was being injected deactivated.

My MM fork mitigated the ConfigCache problem, but in theory had not solved it - only make it absurdly improbable to happen, so anything that woks on my fork and doesn't on Forum MM I tend to automatically pinpoint Forum's MM as the culprit.

**BUT THIS TIME**, I got screwed by myself because while testing and developing the last Recall release, I was reusing crafts and savegames and so didn't noticed the problem. On the `acp` (acceptance) test bed, I created a new savagame with new crafts and, so, I got bitten by my mistake. But since the `acp` test bed uses Forum's MM, I misdiagnosed the source of the problem - and as we can easily note, I'm **absolutely fed up** with Forum's MM (and some other add'ons) stupidities, and this is interfering with my diagnosing sometimes.

(sigh).

**Comment by nan0bug00** [comment]
Have you ever stopped to consider that maybe you're just not always right and that jumping to conclusions and calling other people's code trash makes you kind of a dick?

**Comment by Lisias** [comment]
> Have you ever stopped to consider that maybe you're just not always right and that jumping to conclusions and calling other people's code trash makes you kind of a dick?

Only when I wrong, my "friend".

By the way:

1. I just considered I'm not always right - in fact, my last post is essentially an admission that I was wrong. This time.
2. Module Manager is a hell of a shitty code. Bad design decisions, bad implementations, bad attitude of the authors. Just like yours, by the way. :)
